### ISSUE TITLE
Expanding properties on some CRDs breaks page rendering with a "The language "undefined" has no grammar." error

### ISSUE THREAD

**Issue by KingJ** [crdsdev/doc#182]
On some CRDs, expanding any of the properties within the CRD's spec will cause the page to go blank other than the very top header;

<img width="2047" alt="image" src="https://github.com/user-attachments/assets/5d06bb1a-1aac-4fce-9299-950d305baf0d">

When this happens, the following error is logged to the browser's console;

```
react-dom.production.min.js:125 Error: The language "undefined" has no grammar.
Please report this to https://github.com/markedjs/marked.
    at Object.highlight (prism-core.min.js:1:3872)
    at e.code (v1beta1@v1.8.3:93:60)
    at e.code (marked.min.js:6:34023)
    at n.parse (marked.min.js:6:30323)
    at Function.parse (marked.min.js:6:29865)
    at se (marked.min.js:6:33474)
    at getDescription (v1beta1@v1.8.3:111:35)
    at SchemaPart (v1beta1@v1.8.3:209:118)
    at v1beta1@v1.8.3:213:33
    at Array.map (<anonymous>)
```

I've been able to consistently trigger this with the [kubernetes-sigs/cluster-api@v1.8.3 KubeadmControlPlane.v1beta1.controlplane.cluster.x-k8s.io CRD](https://doc.crds.dev/github.com/kubernetes-sigs/cluster-api/controlplane.cluster.x-k8s.io/KubeadmControlPlane/v1beta1@v1.8.3) on Firefox 130.0.1, Chrome 129.0.6668.70, and Safari on macOS 14.6.1.

**Comment by pawcykca** [comment]
@hasheddan could you look at this issue? ;-)

**Comment by kukacz** [comment]
I'm experiencing this same error, it practically breaks displaying of affected resources. It happens on newer versions of some resource but not in older versions of the same - maybe those older ones were built and cached with previous healthy version? Easily reproducible by expanding any item or all of them:

This one is broken: https://doc.crds.dev/github.com/kubernetes-sigs/cluster-api/controlplane.cluster.x-k8s.io/KubeadmControlPlane/v1beta1@v1.9.1
While the older version works: https://doc.crds.dev/github.com/kubernetes-sigs/cluster-api/controlplane.cluster.x-k8s.io/KubeadmControlPlane/v1beta1@v1.6.8

**Comment by djpbessems** [comment]
This has been happening for months already. I would've filed a bug before had I known this was the respective repository to do so.

**Comment by hellt** [comment]
I have the same, and it looks like prism is not getting downloaded?

<img width="2142" height="1444" alt="Image" src="https://github.com/user-attachments/assets/94798f51-ba76-4006-8b01-1a2a4a768eae" />

**Comment by frandominguezl** [comment]
@hasheddan This is still an issue and honestly it makes the project useless. Is this project unmaintained? Would you be willing to accept PRs?

**Comment by Raboo** [comment]
I got the same problem.
Tried Firefox, Chrome, Edge.

```
Resrouce from “https://unpkg.com/prismjs@1.30.0/components/prism-undefined.min.js” blocked because of MIME-type (“text/plain”) imbalance (X-Content-Type-Options: nosniff). v2@1.18.4
Loading failed for <script> with source “https://unpkg.com/prismjs@1/components/prism-undefined.min.js”. v2@1.18.4:1:1
Error: The language "undefined" has no grammar.
Please report this to https://github.com/markedjs/marked.
    highlight https://unpkg.com/prismjs@1/components/prism-core.min.js:1
    code https://doc.crds.dev/github.com/cilium/cilium/cilium.io/CiliumNetworkPolicy/v2@1.18.4:93
    i https://unpkg.com/marked@1.2.4/marked.min.js:6
    parse https://unpkg.com/marked@1.2.4/marked.min.js:6
    parse https://unpkg.com/marked@1.2.4/marked.min.js:6
    parse https://unpkg.com/marked@1.2.4/marked.min.js:6
    se https://unpkg.com/marked@1.2.4/marked.min.js:6
    getDescription https://doc.crds.dev/github.com/cilium/cilium/cilium.io/CiliumNetworkPolicy/v2@1.18.4:111
    SchemaPart https://doc.crds.dev/github.com/cilium/cilium/cilium.io/CiliumNetworkPolicy/v2@1.18.4:209
    SchemaPart https://doc.crds.dev/github.com/cilium/cilium/cilium.io/CiliumNetworkPolicy/v2@1.18.4:213
    SchemaPart https://doc.crds.dev/github.com/cilium/cilium/cilium.io/CiliumNetworkPolicy/v2@1.18.4:213
    SchemaPart https://doc.crds.dev/github.com/cilium/cilium/cilium.io/CiliumNetworkPolicy/v2@1.18.4:213
    SchemaPart https://doc.crds.dev/github.com/cilium/cilium/cilium.io/CiliumNetworkPolicy/v2@1.18.4:213
    SchemaPart https://doc.crds.dev/github.com/cilium/cilium/cilium.io/CiliumNetworkPolicy/v2@1.18.4:213
    SchemaPart https://doc.crds.dev/github.com/cilium/cilium/cilium.io/CiliumNetworkPolicy/v2@1.18.4:213
    SchemaPart https://doc.crds.dev/github.com/cilium/cilium/cilium.io/CiliumNetworkPolicy/v2@1.18.4:213
    SchemaPart https://doc.crds.dev/github.com/cilium/cilium/cilium.io/CiliumNetworkPolicy/v2@1.18.4:213
    CRD https://doc.crds.dev/github.com/cilium/cilium/cilium.io/CiliumNetworkPolicy/v2@1.18.4:135
    CRD https://doc.crds.dev/github.com/cilium/cilium/cilium.io/CiliumNetworkPolicy/v2@1.18.4:135
    React 17
react-dom.production.min.js:125:24
    React 20
```

Can't really use the site as it is...

**Comment by willemm** [comment]
Given that https://unpkg.com/prismjs@1.30.0/components/prism-undefined.min.js returns a 404-NotFound, it seems like it would be broken for everyone.

**Comment by Raboo** [comment]
I actually switched to https://crds.r8y.page/ (https://github.com/ripta/crds-dev-doc) which is a maintained fork.
